# Generated by Django 4.2 on 2025-01-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
