# Generated by Django 4.2 on 2025-01-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_delete_mymodel"),
    ]

    operations = []
